DROP DATABASE IF EXISTS RHCONTROLLER;
CREATE DATABASE RHCONTROLLER;
USE RHCONTROLLER;

CREATE TABLE ESTADO_CIVIL(
	ID_ESTADO_CIVIL INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(20),
    PRIMARY KEY(ID_ESTADO_CIVIL)
    );
    
CREATE TABLE SEXO(
	ID_SEXO INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(20),
    PRIMARY KEY(ID_SEXO)
    );

